# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "remix-qr-test-app"
client_id = "90e98b6456f65eba1c983bdd603007ad"
application_url = "https://visit-reef-suggestion-girlfriend.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://visit-reef-suggestion-girlfriend.trycloudflare.com/auth/callback",
  "https://visit-reef-suggestion-girlfriend.trycloudflare.com/auth/shopify/callback",
  "https://visit-reef-suggestion-girlfriend.trycloudflare.com/api/auth/callback",
  "https://visit-reef-suggestion-girlfriend.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-remix-app.myshopify.com"
