# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "remix-qr-test-app-staging"
client_id = "e1df8f1b592f9f832ed71aecb0374dba"
application_url = "https://shopify-remix-test-app-git-staging-spencersmb-s-team.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_customers, write_customers, read_discounts"

[auth]
redirect_urls = [
  "https://shopify-remix-test-app-git-staging-spencersmb-s-team.vercel.app/auth/callback",
  "https://shopify-remix-test-app-git-staging-spencersmb-s-team.vercel.app/auth/shopify/callback",
  "https://shopify-remix-test-app-git-staging-spencersmb-s-team.vercel.app/api/auth/callback",
  "https://shopify-remix-test-app-git-staging-spencersmb-s-team.vercel.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-remix-app.myshopify.com"
